export const putEmail = 'Enter an email'
export const putValidEmail= 'Enter a valid email'
export const putPassword = 'Enter a password'
export const putValidPassword = 'Tha password must have at least 6 characters'
export const userOk = 'Invalid user'
export const userNotOk = 'Unregistered user'
export const userDeleted = 'Deleted user'
export const error = 'ERROR'
export const dontHaveACount = 'You do not have an account?'
export const alreadyHaveACount = 'Do you already have an account?'
export const wrongPassword = 'The password is invalid or the user does not have a password'
export const user = 'User'
export const password = 'Password'
export const confirmPassword = 'Confirm password'
export const email = 'Email'
export const enter = 'ENTER'
export const registerButton = 'REGISTER'
export const register = 'Register'
export const userCreated = 'User created'
export const userAlreadyInUse = 'User already exits in Firebase'
export const userNotCreated = 'User does not exits in Firebase'
export const equalsPasswords = 'Both passwords must be equals'
export const beginSession = 'log in'
export const passwordForgotten = 'Have you forgotten your password?'
export const recoverPass = 'Recover password'
export const invalidEmail = 'The email is invalid'
export const emailSended = 'An email is sended to your account. Please, follow the instructions.'

//MENU
export const logout = 'LOGOUT'
export const sign = 'Sign'
export const adjust = 'Adjust'
export const myMouvements = 'Mouvements'

//APP.JS
export const menu = 'Menu'

//SIGN AT WORK
export const inputSigned = 'Signed INPUT'
export const outputSigned = 'Signed OUTPUT'
export const notReadable = 'System to be readed is not visible'
export const notSystem = 'THERE ARE NOT SYSTEM BOUNDED'
export const goConfig = 'Go to Adjust an bound a system'
export const input = 'INPUT'
export const output = 'OUTPUT'
export const errorSavingMouvement = 'Error saving the information. Try again.'

//ADJUST
export const systemSelected = 'System selected'
export const ok = 'OK'
export const systemBounded = 'Systen bounded in DDBB'
export const errorBounding = 'Error bounding system and user.'
export const selectSystem = 'Select system - '
export const notBoundedSystems = 'No linkable systems'
export const searchSystem = 'Search and link system'
export const systemAlreadyBounded = 'There ia a system linked'
export const unboundSystem = 'Desenlazar equipo'

//MY MOUVEMENTS